name: dockerfile

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  dockerfile:
    name: Run Dockerfiles in examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run example - simple
        run: |
          docker build -t simple -f ./_example/simple/Dockerfile .
          docker run simple | grep 99\ こんにちは世界099
